version: '3.1'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'M12345678'
      MYSQL_DATABASE: 'MotorcycleMarket'
      MYSQL_USER: 'MotorcycleMarket'
      MYSQL_PASSWORD: 'M12345678'
    volumes:
      - 'mysql:/var/lib/mysql'
    ports:
      - 3307:3306

volumes:
  mysql: